### ISSUE TITLE
The X-axis vibration motor shows an undesired sluggishness in touch feedback

### ISSUE THREAD

**Issue by Stillrain577681223** [flakeforever/device_xiaomi_mondrian#11]
Under normal circumstances, the motor should have clear and loud touch feedback, but it experiences feedback similar to notification vibrations in this regard (only with small force and short duration), which should not be its best performance

**Comment by flakeforever** [comment]
In the new version, a new vibration hardware service is used, which is different from the stock configuration and has been streamlined; I will follow up on this issue.

**Comment by flakeforever** [comment]
[Reorganize vibrator firmwares] to fixed this issue (https://github.com/flakeforever/device_xiaomi_mondrian/commit/74a06d2abc3ad413c984848010beaaaf49e828d2)
