### ISSUE TITLE
Miui camera vendor files

### ISSUE THREAD

**Issue by finex333** [flakeforever/device_xiaomi_mondrian#16]
Hi, where can i find the vendor files for miui camera? Thanks in advance.

**Comment by flakeforever** [comment]
~~From here [vendor_xiaomi_camera-mondrian](https://drive.google.com/open?id=10xqU_XQNWUZP867xGC6L-wfM4AM7E2zI&usp=drive_fs)~~

**Comment by kde-yyds** [comment]
Can you please share it again? The link is 404. Thanks in advance.

**Comment by flakeforever** [comment]
Hi, you can get a new version from this link.
[vendor_xiaomi_miuicamera.zip](https://drive.google.com/file/d/1-5BruAPZCMPiLmNH1joW-OWuXfCFxbpx/view?usp=drive_link)

**Comment by kde-yyds** [comment]
> Hi, you can get a new version from this link. [vendor_xiaomi_miuicamera.zip](https://drive.google.com/file/d/1-5BruAPZCMPiLmNH1joW-OWuXfCFxbpx/view?usp=drive_link)

Thanks!

**Comment by kde-yyds** [comment]
![Screenshot_20241102-220801_Settings.png](https://github.com/user-attachments/assets/cc364498-623c-401d-9525-85f4e2b25394)

It's working on Android 15!

**Comment by flakeforever** [comment]
Great news, thank you.
