### ISSUE TITLE
The fingerprint text suggest was covered by fingerprint icon.

### ISSUE THREAD

**Issue by flakeforever** [flakeforever/device_xiaomi_mondrian#5]
![_20231219141622](https://github.com/flakeforever/device_xiaomi_mondrian/assets/113103193/d025e3e1-b299-42cd-8c0a-628eaa131e3a)

**Comment by Gosth15** [comment]
Hello I think this icon looks a little better for the Fod and it has a movement effect both in Aod and in the lockscreen. and thus it does not cover the text.

Commit: [ tested ✔️ ]
https://github.com/Gosth15/frameworks_base/commit/948f5e879425efac3d899be21ef51cd64d80a1f5
![IMG_20240113_092638_829](https://github.com/flakeforever/device_xiaomi_mondrian/assets/104647519/d945b3cd-b5fa-44c1-bc45-b0c93bd5df31)

**Comment by flakeforever** [comment]
Thank you very much for providing this.

**Comment by Gosth15** [comment]
I hope it helps you something.

**Comment by flakeforever** [comment]
[Import breathing UDFPS animation from nothingOS](https://github.com/flakeforever/device_xiaomi_mondrian/commit/c8b51e9cb8710d25ba56b6754481b1f359e131f0)
