### ISSUE TITLE
vendor.img

### ISSUE THREAD

**Issue by Fauxly** [flakeforever/device_xiaomi_mondrian#8]
Hi 

tell me how to unpack and repack vendor.img? 
tnx

**Comment by flakeforever** [comment]
https://github.com/affggh/NH4RomTool.git
I use this one, it's great. Only [an issue with packaging of ext4](https://github.com/affggh/NH4RomTool/issues/1). So you can use packaging of  erofs.

**Comment by Fauxly** [comment]
tnx bro!!!

**Comment by flakeforever** [comment]
After packaging, you still need to manually repair vbmeta.

For example:
`avbtool add_hashtree_footer --image vendor.img --partition_name vendor --partition_size 1621893120 --key ~/android/lineage/external/avb/test/data/testkey_rsa4096.pem --hash_algorithm sha256 --fec_num_roots 2 --prop_from_file com.android.build.vendor.fingerprint:prop/fingerprint.prop --prop_from_file com.android.build.vendor.os_version:prop/os_version.prop --prop_from_file com.android.build.vendor.security_patch:prop/security_patch.prop`

**Comment by Fauxly** [comment]
Hi need help
![IMG_20240115_195033.jpg](https://github.com/flakeforever/device_xiaomi_mondrian/assets/509642/4dcc3d64-93d7-4387-bf71-29553a5c01b4)

which ones should you choose?
