### ISSUE TITLE
Hi need help

### ISSUE THREAD

**Issue by Fauxly** [flakeforever/device_xiaomi_mondrian#9]
Hi need help
![IMG_20240115_195033.jpg](https://github.com/flakeforever/device_xiaomi_mondrian/assets/509642/4dcc3d64-93d7-4387-bf71-29553a5c01b4)

which ones should you choose?

_Originally posted by @Fauxly in https://github.com/flakeforever/device_xiaomi_mondrian/issues/8#issuecomment-1892584686_

**Comment by flakeforever** [comment]
I haven't used this tool before, but I think "Process vbmetas" might be necessary?
